### ISSUE TITLE
bcl2fastq.index_summary: Crash when 180810_M00753_0053_000000000-D4HKJ is selected

### ISSUE THREAD

**Issue by slazicoicr** [oicr-gsi/dashi#4]
Selecting 180810_M00753_0053_000000000-D4HKJ causes an exception:

```
Traceback (most recent call last):
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/dash/dash.py", line 1152, in dispatch
    response.set_data(self.callback_map[output]['callback'](*args))
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/dash/dash.py", line 1038, in add_context
    output_value = func(*args, **kwargs)
  File "/home/slazic/Documents/Code/2018-08-27-Dash_trial/bcl2fastq/index_summary.py", line 96, in update_known_index_bar
    run['index'] = run['Index1'].str.cat(
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/pandas/core/generic.py", line 5063, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/pandas/core/accessor.py", line 171, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/pandas/core/strings.py", line 1796, in __init__
    self._validate(data)
  File "/home/slazic/.local/miniconda3/envs/work3.6/lib/python3.6/site-packages/pandas/core/strings.py", line 1818, in _validate
    raise AttributeError("Can only use .str accessor with string "
AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas
```

**Comment by slazicoicr** [comment]
Exploring this bug in #16 shows it to be due to data integrity issues. The run has libraries that lack both indices, which should not be possible with bcl2fastq.

Dashi should not have to deal with data sanity issues on top of the difficult task of visualizing them. I think this issue belongs with GSI-QC-ETL.
